#!/bin/bash
# This file is part of BuildBox project
# Copyright (C) 2020-2026 Trusted Objects

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 2, as published by the Free Software Foundation.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, see
# <https://www.gnu.org/licenses/>.

source buildbox_utils.sh

function help {
	echo "Usage: bbx fetch [-u|--update] <PKG...>"
	echo ""
	echo "Fetch (clone) package sources for the current target."
	echo "  PKG...           Package name(s) to fetch (glob patterns supported)"
	echo "  -u, --update     Update the sources already fetched, when they can"
	echo "                   move, instead of leaving them as they are"
}

case "$1" in
	help|-h|--help) help; exit 0 ;;
esac

update=0
packages_list=()
while [ $# -gt 0 ]; do
	case "${1}" in
		-u|--update)
			update=1
			;;
		-*)
			>&2 echo "Unknown option ${1}"
			exit 1
			;;
		*)
			packages_list+=("${1}")
			;;
	esac
	shift
done

if [ ${#packages_list[@]} -lt 1 ]; then
	help >&2
	exit 1
fi
if [ -z "${BB_PROJECT_DIR}" ] || [ ! -d "${BB_PROJECT_DIR}" ]; then
	>&2 echo "Not in a BuildBox project directory"
	exit 1
fi

bb_trap_errors_nolog

cd ${BB_PROJECT_DIR}
mkdir -p ${BB_TARGET_SRC_DIR}
source $(bb_get_target_profile_path ${BB_TARGET})

# Select packages matching given list, and make results unique
selected_packages=$(bb_find_matching_packages 1 "${packages_list[@]}")
if [ "${selected_packages}" == "" ]; then
	>&2 echo "No matching packages !"
	exit 1
fi

# Packages lock (lock automatically released on process end)
bb_lock_acquire ${BB_PROJECT_SRC_DIR}/lock "(waiting ongoing packages operations to end...)"
if [ $? -ne 0 ]; then
	>&2 echo "Unable to acquire sources lock !"
	exit 1
fi

# Clone individual packages
total_warning_count=0
while read -r line
do
	readarray -d : -t package <<< "${line}"
	pkg_name=${package[0]/$'\n'/}
	# bb_is_package_cloned returns 1 when the package is cloned. Calling it
	# through '||' also keeps the error trap out of the way, its return code
	# carrying an answer rather than a failure
	cloned=0
	bb_is_package_cloned ${BB_TARGET} ${pkg_name} || cloned=1
	if [ ${update} -eq 1 ] && [ ${cloned} -eq 1 ]; then
		echo "Updating ${pkg_name} ..."
		# Same reason for '||': 2 and 3 tell what happened, they are not
		# failures. bb_update_package says what it did on stdout.
		ret=0
		bb_update_package ${pkg_name} || ret=$?
		if [ ${ret} -ne 0 ] && [ ${ret} -ne 2 ] && [ ${ret} -ne 3 ]; then
			>&2 echo "Unable to update ${pkg_name} !"
			exit 1
		fi
	else
		echo "Cloning ${pkg_name} ..."
		bb_clone_package ${pkg_name}
	fi
	echo
done < <(echo "${selected_packages}")

echo "Done."
exit 0
