#!/bin/bash

source buildbox_utils.sh

function help {
	echo "Usage: bbx pkg [-v] <PKG...>"
	echo ""
	echo "Show package information."
	echo "  -v       Verbose output"
	echo "  PKG...   Package name(s)"
}

case "$1" in
	help|-h|--help) help; exit 0 ;;
esac

if [ -z "${BB_PROJECT_DIR}" ] || [ ! -d "${BB_PROJECT_DIR}" ]; then
	>&2 echo "Not in a BuildBox project directory"
	exit 1
fi

if [ $# -lt 1 ]; then
	help >&2
	exit 1
fi
verbose=0
packages=""
while getopts "v" OPTION; do
	case $OPTION in
	v)
		verbose=1
		;;
	*)
		>&2 echo "Invalid parameters, please read man page"
		exit 1
		;;
	esac
done
shift $(( OPTIND - 1 ))
packages_list="$@"

# Select packages matching given list, and make results unique
selected_packages="$(bb_find_matching_packages 1 ${packages_list})"
if [ "${selected_packages}" == "" ]; then
	>&2 echo "No matching packages !"
	exit 1
fi

# Print packages information
while read -r line
do
	readarray -d : -t package <<< "${line}"
	pkg_name=${package[0]/$'\n'/}
	pkg_opts=${package[1]/$'\n'/}
	_pkg ${pkg_name} "${pkg_opts}" ${verbose}
done < <(echo "${selected_packages}")

exit 0
