#!/bin/bash
# This file is part of BuildBox project
# Copyright (C) 2020-2026 Trusted Objects

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 2, as published by the Free Software Foundation.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, see
# <https://www.gnu.org/licenses/>.

source _pre_cmd

source buildbox_utils.sh

options=$@
if [ -z ${BB_TARGET} ]; then
	echo "Please set current project target with 'target set <name>'"
	exit 1
fi
target_path=$(bb_get_target_profile_path ${BB_TARGET})
if [ -z ${target_path} ]; then
	echo "Project target ${BB_TARGET} not found !"
	exit 1
fi

while read -r pkg_name; do
	bb_clean_package ${pkg_name} > /dev/null 2>&1
done < <(bb_get_packages ${BB_TARGET})
rm -rf ${BB_TARGET_BUILD_DIR} > /dev/null 2>&1

echo "Target ${BB_TARGET} clean."
