#!/bin/bash
# This file is part of BuildBox project
# Copyright (C) 2020-2026 Trusted Objects

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 2, as published by the Free Software Foundation.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, see
# <https://www.gnu.org/licenses/>.

source _pre_cmd

source buildbox_utils.sh

if [ -z ${BB_TARGET} ]; then
	echo "Please set current project target with 'target set <name>'"
	exit 1
fi
if [ -z "${BB_TARGET_BUILD_DIR}" ] || [ ! -d ${BB_TARGET_BUILD_DIR} ]; then
	echo "Target must be built before running tests !"
	exit 1
fi

source $(bb_get_target_profile_path ${BB_TARGET})
if [ -z ${TESTS} ]; then
	echo "No target tests !"
	echo "Define TESTS in target profile file."
	exit 1
fi

tests_log_file="${BB_TARGET_DIR}/tests.log"
bb_set_current_log_file "${tests_log_file}"

# Quiet mode
if [[ "${1}" == "-q" ]]; then
	quiet=1
	shift
fi

options=$@

function cleanup {
	# Restore initial target, if changed
	bb_restore_last_target
}
function error {
	cleanup
	bb_error
}
bb_trap_errors_custom error
bb_clear_log_file
bb_save_last_target

echo "Tests logs are available at ${tests_log_file}"
echo -n "Testing ${BB_TARGET} target ... "
if [ -n "$quiet" ]; then
	# Use the hack below to prevent malformed scripts to seek on output file
	# The pipe makes seeking impossible on output file.
	bb_enable_log_file
	set -o pipefail
	${TESTS} ${options} 2>&1 | cat
	set +o pipefail
	bb_disable_log_file
else
	echo
	set -o pipefail
	${TESTS} ${options} 2>&1 | tee -a "${tests_log_file}"
	set +o pipefail
fi

cleanup

echo -e "\e[32mSuccess\e[0m."
