#!/bin/bash
source _pre_cmd

source buildbox_utils.sh

options=$@
if [ -z ${BB_TARGET} ]; then
	echo "Please set current project target with 'target set <name>'"
	exit 1
fi
target_path=$(bb_get_target_profile_path ${BB_TARGET})
if [ -z ${target_path} ]; then
	echo "Project target ${BB_TARGET} not found !"
	exit 1
fi
if [ ! -d ${BB_TARGET_DIR} ]; then
	echo "Target ${BB_TARGET} is already wiped."
	exit 0
fi

bb_confirm "Wipe project target ${BB_TARGET} sources and built files?"
if [ $? -eq 0 ]; then
	exit 0
fi

# Remove built files definitively
bb_unload_tools
bb_run_tools_cleanup_hook
while read -r pkg_name; do
	bb_wipe_package ${pkg_name} > /dev/null 2>&1
done < <(bb_get_packages ${BB_TARGET})
# Ensure all directories have search bit to be able to remove all
if [ -d ${BB_TARGET_BUILD_DIR} ]; then
	chmod -R u+rwX ${BB_TARGET_BUILD_DIR} > /dev/null 2>&1
	rm -rf ${BB_TARGET_BUILD_DIR}
fi
# Trash remaining files
bb_trash ${BB_TARGET_DIR} > /dev/null
bb_load_tools

echo "Target ${BB_TARGET} wiped."
