#!/bin/bash
# This file is part of BuildBox project
# Copyright (C) 2020-2026 Trusted Objects

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 2, as published by the Free Software Foundation.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, see
# <https://www.gnu.org/licenses/>.

source _pre_cmd

source buildbox_utils.sh

if [ -z ${BB_TARGET} ]; then
	echo "Please set current project target with 'target set <name>'"
	exit 1
fi

log_file="${BB_TARGET_DIR}/${BB_API_CALLER}.log"
bb_set_current_log_file "${log_file}"

mkdir -p ${BB_TARGET_DIR}

cmd=$(basename ${0})
continue_build=0
verbose=0
while [ -n "${1}" ]; do
	case "${1}" in
		-c|--continue)
			# Continue failed build
			continue_build=1
			shift
			;;
		-v)
			verbose=1
			shift
			;;
		*)
			>&2 echo "Unknown option ${1}"
			exit 1
			;;
	esac
done
if [ ${continue_build} -eq 1 ]; then
	if [ ! -f ${BB_TARGET_DIR}/target_build.step ]; then
		echo -e "\e[33mWarning:\e[0m there is no build to continue, starting from beginning"
	else
		last_succeed_step=$(cat ${BB_TARGET_DIR}/target_build.step)
	fi
fi

bb_trap_errors
bb_clear_log_file

cd ${BB_PROJECT_DIR}
mkdir -p ${BB_TARGET_SRC_DIR}
mkdir -p ${BB_TARGET_BUILD_DIR}
source $(bb_get_target_profile_path ${BB_TARGET})
bb_set_local_env ${BB_TARGET_BUILD_DIR} ${CPU}

# Packages lock (lock automatically released on process end)
bb_lock_acquire ${BB_PROJECT_SRC_DIR}/lock "(waiting ongoing packages operations to end...)"
if [ $? -ne 0 ]; then
	echo "Unable to acquire sources lock !"
	exit 1
fi

if [ -n "${TOOLS}" ]; then
	echo -e "Cloning \e[1m${BB_TARGET}\e[0m target required tools... "
	while read -r tool_name; do
		if [ ${verbose} -eq 0 ]; then
			echo -e -n "\t${tool_name} ... "
			bb_enable_log_file
			bb_clone_tool ${tool_name}
			bb_disable_log_file
			echo -e "\e[32mok\e[0m"
		else
			set -o pipefail
			echo "Cloning ${tool_name}..."
			bb_clone_tool ${tool_name} 2>&1 | tee -a "${log_file}"
			echo -e "\e[32mOK\e[0m, ${tool_name} cloned."
			set +o pipefail
		fi
	done < <(bb_get_tools)
fi
bb_load_tools

total_warning_count=0
while read -r line; do
	readarray -d : -t package <<< "${line}"
	pkg_name=${package[0]/$'\n'/}
	pkg_opts=${package[1]/$'\n'/}
	if [ ${verbose} -eq 0 ] || [ -z "${pkg_opts}" ]; then
		echo -n "Building ${pkg_name} ... "
	else
		echo "Building ${pkg_name}, options: ${pkg_opts}..."
	fi
	if [ -z ${last_succeed_step} ]; then
		if [ ${verbose} -eq 0 ]; then
			bb_enable_log_file
			if [ "${cmd}" != "target_fastbuild" ]; then
				bb_build_package ${pkg_name} ${pkg_opts}
			else
				bb_build_package_fast ${pkg_name} ${pkg_opts}
			fi
			bb_disable_log_file
		else
			set -o pipefail
			if [ "${cmd}" != "target_fastbuild" ]; then
				bb_build_package ${pkg_name} ${pkg_opts} 2>&1 | tee -a "${log_file}"
			else
				bb_build_package_fast ${pkg_name} ${pkg_opts} 2>&1 | tee -a "${log_file}"
			fi
			set +o pipefail
		fi
		warning_count=$(bb_stat_package ${pkg_name} warning)
		if [ -n "${warning_count}" ]; then
			if [ ${warning_count} -eq 0 ]; then
				if [ ${verbose} -eq 0 ]; then
					echo -e "\e[32mok\e[0m"
				else
					echo -e "\e[32mOK\e[0m, ${pkg_name} built."
				fi
			else
				if [ ${verbose} -eq 0 ]; then
					echo -e "\e[35m${warning_count} warning(s)\e[0m"
				else
					echo -e "${pkg_name} built with \e[35m${warning_count} warning(s)\e[0m."
				fi
			fi
			total_warning_count=$((${total_warning_count}+${warning_count}))
		else
			if [ ${verbose} -eq 0 ]; then
				echo -e "\e[32mok\e[0m"
			else
				echo -e "\e[32mOK\e[0m, ${pkg_name} built."
			fi
		fi
		echo ${pkg_name} > ${BB_TARGET_DIR}/target_build.step
	else # continue build from last failed step
		if [[ "${pkg_name}" == "${last_succeed_step}" ]]; then
			unset last_succeed_step
		fi
		if [ ${verbose} -eq 0 ]; then
			echo -e "\e[33mskip\e[0m"
		else
			echo -e "\e[33mSkipped\e[0m ${pkg_name} build."
		fi
	fi
done < <(bb_get_packages_with_options ${BB_TARGET})
rm -f ${BB_TARGET_DIR}/target_build.step

if [ ${total_warning_count} -eq 0 ]; then
	echo "Done."
else
	echo -e "Done, with \e[35m${total_warning_count} warning(s)\e[0m"
fi
