#!/bin/bash
source _pre_cmd

source buildbox_utils.sh

if [ -z ${BB_TARGET} ]; then
	echo "Please set current project target with 'target set <name>'"
	exit 1
fi

# Get TOOLS var
source $(bb_get_target_profile_path ${BB_TARGET})

if [ -f ${BB_PROJECT_PROFILE_DIR}/${TOOLS} ]; then
	while read -r line; do
		readarray -d : -t tool <<< "${line}"
		tool_name=${tool[0]/$'\n'/}
		_tool ${tool_name}
	done < <(bb_get_tools)
else
	echo "No tools required for this target"
fi
