#!/bin/bash
# This file is part of BuildBox project
# Copyright (C) 2020-2026 Trusted Objects

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 2, as published by the Free Software Foundation.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, see
# <https://www.gnu.org/licenses/>.

source _pre_cmd

source buildbox_utils.sh

options=$@

if [ -z ${BB_TARGET} ]; then
	echo "Please set current project target with 'target set <name>'"
	exit 1
fi
if [ -z "${BB_TARGET_BUILD_DIR}" ] || [ ! -d ${BB_TARGET_BUILD_DIR} ]; then
	echo "Target must be built !"
	exit 1
fi
if [ -z "${BB_PREBUILT_SERVER}" ]; then
	echo "Please define BB_PREBUILT_SERVER in ${BB_CUSTOM_CONFIG}, and reopen BuildBox shell"
	exit 1
fi
if [ -z "${BB_PREBUILT_USERNAME}" ]; then
	echo "Please define BB_PREBUILT_USERNAME in ${BB_CUSTOM_CONFIG}, and reopen BuildBox shell"
	exit 1
fi
if [ -z "${BB_PREBUILT_PATH}" ]; then
	echo "Please define BB_PREBUILT_PATH in ${BB_CUSTOM_CONFIG}, and reopen BuildBox shell"
	exit 1
fi

archive_dir=
function cleanup {
	if [ -d "${archive_dir}" ]; then
		rm -r "${archive_dir}"
	fi
}
function error {
	cleanup
	bb_error
}
bb_trap_errors_custom error

echo -n "Archiving built files... "
archive_dir=$(bb_archive_prebuilt_target)
echo -e "\e[32mok\e[0m"
echo -n "Releasing archive... "
bb_export_prebuilt_target "${archive_dir}"
echo -e "\e[32mok\e[0m"
cleanup
